export const UPDATE_WEATHER_LOADING_STATE = "UPDATE_WEATHER_LOADING_STATE"
export const UPDATE_FORECAST_LOADING_STATE = "UPDATE_FORECAST_LOADING_STATE"
export const UPDATE_WEATHER_DATA = "UPDATE_WEATHER_DATA"
export const UPDATE_FORECAST_DATA = "UPDATE_FORECAST_DATE"
export const UPDATE_LOCATION = "UPDATE_LOCATION"

export const LS_COORDS_LAT = 'coords_lat'
export const LS_COORDS_LON = 'coords_lon'

export const DATE_FORMAT_DATE = 'DATE'
export const DATE_FORMAT_TIME = 'TIME'
